const questoes_quiz = [
    {
    questoes: 'qual meu prato de comida preferido',
    a: 'arros,feijao,ovo frito',
    b: 'arroz e bife aparmdna',
    c: 'strogonof de frango',
    d: 'strogonof de carne',
    correta: 'c',
    },

    {
    questoes: 'qual carro eu prefiro',
    a: 'feerrari',
    b: 'bmw',
    c: 'porche',
    d: 'nissan',
    correta: 'd',
    },
    {
    questoes: 'qual e anime eu prefiro entre esses',
    a: 'one pirce',
    b: 'naruto',
    c: 'demons leier',
    d: 'felimi x spy',
    correta: 'c',
    },
    {
    questoes: 'qual e a melhor raça de cachorro para tocar gado',
    a: 'border coliie',
    b: 'spit alemao',
    c: 'buslaitier',
    d: 'pastor alemao',
    correta: 'A',
    },
    {
    questoes: 'quem eu salvaria ',
    a: 'um cachorro ',
    b: 'uma pessoa qualquer ',
    c: 'uma peesoa da minha escola',
    d: 'minha professora de portugues que paasa trarefa na sexta para entregar segunda',
    correta: 'a',
    },
    {
    questoes: 'qual materia e minha preferida ',
    a: 'PORTUGUES!!!!!!',
    b: 'ciencias',
    c: 'historia',
    d: 'nem uma pq sao todas chatas',
    correta: 'b',
    },
    {
    questoes: 'sabemdo as questoes acima,qual materia eu escluiria',
    a: 'portugues',
    b: 'ciencia',
    c: 'historia',
    d: 'orientaçao de estudos',
    correta: 'd',
    },
    {
    questoes: 'qual e minha paixao',
    a: 'ir na robotica',
    b: 'acordar cedo para lavar louça',
    c: 'ir ver minha diretora',
    d: 'tomar um sorvete do mc ou do bk nos dias quentes e assistir you cine no celular no ar condicionado',
    correta: 'a',
    },
    {
    questoes: 'quando eu faço um quiz eu espero que',
    a: 'responda tudo',
    b: 'ler tudo pelo menos',
    c: 'tanto faz pq isso nao muda minha vida',
    d: 'tabom',
    correta: '',
    },
    {
    questoes: '',
    a: '',
    b: ' ',
    c: '',
    d: '',
    correta: '',
    },
]